[package]
name = "ferrum-alloc-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.ferrum-alloc]
path = ".."

[[bin]]
name = "alloc_free_loop"
path = "fuzz_targets/alloc_free_loop.rs"
test = false
doc = false
